name: 'Test Eyes'
description: 'Collect test results and deploy analytics dashboard'
author: 'goldbergyoni'

inputs:
  junit-path:
    description: 'Path to JUnit XML file'
    required: true
  cache_duration_in_minutes:
    description: 'Cache duration (reserved for future)'
    required: false
    default: '60'

runs:
  using: composite
  steps:
    - name: Validate input
      shell: bash
      run: |
        if [ ! -f "${{ inputs.junit-path }}" ]; then
          echo "::error::File not found: ${{ inputs.junit-path }}"
          exit 1
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Collect test data and deploy
      shell: bash
      env:
        JUNIT_PATH: ${{ inputs.junit-path }}
        GITHUB_SHA: ${{ github.sha }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        # Copy action-dist to temp before branch switching
        cp -r "$ACTION_PATH/action-dist" /tmp/test-eyes-dist

        # Run the bundled collector script
        node "$ACTION_PATH/action-dist/scripts/collector.mjs" \
          --junit-path "$JUNIT_PATH" \
          --commit-sha "$GITHUB_SHA" \
          --data-branch "gh-data"

        # Deploy using the bundled deploy script
        node /tmp/test-eyes-dist/scripts/deploy.mjs \
          --dist-dir /tmp/test-eyes-dist \
          --data-dir data \
          --commit-sha "$GITHUB_SHA" \
          --target-branch "gh-pages"

        # Restore original commit so action.yml exists for post-run
        git checkout "$GITHUB_SHA" 2>/dev/null || true
