name: 'Test Eyes'
description: 'Visual test analytics dashboard - parse JUnit, aggregate stats, deploy to GitHub Pages in one step'
author: 'goldbergyoni'

branding:
  icon: 'eye'
  color: 'blue'

inputs:
  junit-path:
    description: 'Path to JUnit XML file'
    required: true
  post-comment:
    description: 'Post PR comment with link to report (default: true)'
    required: false
    default: 'true'
  github-token:
    description: 'GitHub token for API access (default: GITHUB_TOKEN)'
    required: false
    default: ${{ github.token }}

outputs:
  report-url:
    description: 'URL to the deployed test report on GitHub Pages'

runs:
  using: 'node20'
  main: 'apps/github-action/dist/index.js'
