name: 'Test Eyes'
description: 'Collect test results and aggregate statistics for the Test Eyes dashboard'

inputs:
  data-dir:
    description: 'Path to the directory containing raw test JSON files'
    required: true

outputs:
  aggregated-file:
    description: 'Path to the generated aggregated JSON file'
    value: ${{ steps.aggregate.outputs.output-file }}

runs:
  using: 'composite'
  steps:
    - name: Aggregate test data
      id: aggregate
      uses: ./.github/actions/aggregate-test-data
      with:
        data-dir: ${{ inputs.data-dir }}
