name: 'Test Eyes'
description: 'Collect test results and deploy analytics dashboard'
author: 'goldbergyoni'

inputs:
  junit-path:
    description: 'Path to JUnit XML file'
    required: true
  cache_duration_in_minutes:
    description: 'Cache duration (reserved for future)'
    required: false
    default: '60'

runs:
  using: composite
  steps:
    - name: Validate input
      shell: bash
      run: |
        if [ ! -f "${{ inputs.junit-path }}" ]; then
          echo "::error::File not found: ${{ inputs.junit-path }}"
          exit 1
        fi

    - name: Parse JUnit XML
      shell: bash
      run: node ${{ github.action_path }}/action-dist/scripts/parse-junit.mjs "${{ inputs.junit-path }}" test-data.json

    - name: Commit and aggregate
      shell: bash
      env:
        ACTION_SCRIPTS: ${{ github.action_path }}/action-dist/scripts
        ACTION_DIST: ${{ github.action_path }}/action-dist
      run: |
        # Copy scripts to temp before switching branches
        cp -r "$ACTION_SCRIPTS" /tmp/test-eyes-scripts
        cp -r "$ACTION_DIST" /tmp/test-eyes-dist

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Fetch both branches in one call
        git fetch origin main gh-data 2>/dev/null || git fetch origin main

        # Checkout or create data branch
        git checkout gh-data 2>/dev/null || git checkout --orphan gh-data

        # Setup data directory and copy new test data
        mkdir -p data
        cp ${{ github.workspace }}/test-data.json "data/$(date +%Y-%m-%d)_${GITHUB_SHA:0:7}.json"

        # Run aggregate script from temp location
        node /tmp/test-eyes-scripts/aggregate.mjs data

        # Commit and push data
        git add data/
        git diff --staged --quiet || git commit -m "Add test data for ${GITHUB_SHA:0:7}"
        git push origin gh-data

    - name: Deploy to GitHub Pages
      shell: bash
      run: |
        # Create deploy directory with frontend (from temp copy)
        mkdir -p _site
        cp -r /tmp/test-eyes-dist/* _site/

        # Copy aggregated data
        mkdir -p _site/data
        cp data/main-test-data.json _site/data/

        # Deploy to gh-pages branch
        git checkout --orphan gh-pages-deploy
        git rm -rf . 2>/dev/null || true
        cp -r _site/* .
        rm -rf _site
        touch .nojekyll
        git add .
        git commit -m "Deploy dashboard for ${GITHUB_SHA:0:7}"
        git push origin gh-pages-deploy:gh-pages --force
