name: 'Aggregate Test Data'
description: 'Runs the test-processing aggregation script to produce main-test-data.json'

inputs:
  data-dir:
    description: 'Path to the directory containing raw test JSON files'
    required: true

outputs:
  output-file:
    description: 'Path to the generated aggregated JSON file'
    value: ${{ steps.aggregate.outputs.output-file }}

runs:
  using: 'composite'
  steps:
    - name: Run aggregation script
      id: aggregate
      shell: bash
      run: |
        node "${{ github.action_path }}/../../../apps/test-processing/scripts/aggregate.js" "${{ inputs.data-dir }}"
        echo "output-file=${{ inputs.data-dir }}/main-test-data.json" >> "$GITHUB_OUTPUT"
